name: Build and deploy .NET Azure Function App - sparklinprocessor

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'sparklin/OpenLineage'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          #dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-version: '6.0.x'
          dotnet-quality: 'ga'

      - name: Install Azure Functions
        run: dotnet workload install azure-functions

      - name: install the sdk functions
        run: dotnet add "./sparklin/OpenLineage/OpenLineage/Openlineage.csproj" package Microsoft.NET.Sdk.Functions

      - name: Clean the build
        run: dotnet clean ./sparklin/OpenLineage/OpenLineage/Openlineage.csproj
       
      - name: Restore and build
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_500FDC13760C44898B0475A9DFD74624 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1556FC6A02CD4ABD82D95C9D34CECFF4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DDAFB37CC454F18A4E69F2EA37424FD }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'sparklinprocessor'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
